export const geoList = [
  { id: "GR", name: "그리스" },
  { id: "NG", name: "나이지리아" },
  { id: "ZA", name: "남아프리카" },
  { id: "NL", name: "네덜란드" },
  { id: "NO", name: "노르웨이" },
  { id: "NZ", name: "뉴질랜드" },
  { id: "TW", name: "대만" },
  { id: "KR", name: "대한민국" },
  { id: "DK", name: "덴마크" },
  { id: "DE", name: "독일" },
  { id: "RU", name: "러시아" },
  { id: "RO", name: "루마니아" },
  { id: "MY", name: "말레이시아" },
  { id: "MX", name: "멕시코" },
  { id: "US", name: "미국" },
  { id: "VN", name: "베트남" },
  { id: "BE", name: "벨기에" },
  { id: "BR", name: "브라질" },
  { id: "SA", name: "사우디아라비아" },
  { id: "SE", name: "스웨덴" },
  { id: "CH", name: "스위스" },
  { id: "SG", name: "싱가포르" },
  { id: "AR", name: "아르헨티나" },
  { id: "IE", name: "아일랜드" },
  { id: "GB", name: "영국" },
  { id: "AU", name: "오스트레일리아" },
  { id: "AT", name: "오스트리아" },
  { id: "UA", name: "우크라이나" },
  { id: "IL", name: "이스라엘" },
  { id: "EG", name: "이집트" },
  { id: "IT", name: "이탈리아" },
  { id: "IN", name: "인도" },
  { id: "ID", name: "인도네시아" },
  { id: "JP", name: "일본" },
  { id: "CZ", name: "체코" },
  { id: "CL", name: "칠레" },
  { id: "CA", name: "캐나다" },
  { id: "KE", name: "케냐" },
  { id: "CO", name: "콜롬비아" },
  { id: "TH", name: "태국" },
  { id: "TR", name: "터키" },
  { id: "PT", name: "포르투갈" },
  { id: "PL", name: "폴란드" },
  { id: "FR", name: "프랑스" },
  { id: "FI", name: "핀란드" },
  { id: "PH", name: "필리핀" },
  { id: "HU", name: "헝가리" },
  { id: "HK", name: "홍콩" },
];

export const PORT_NAME = "POPUP_BACKGROUND";
export const GEO_OPTION_KEY = "geoSetting";
